                                        Numpy Assignment Questions

Q1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code that you can use to accomplish various tasks without having to write the code from scratch. Libraries contain modules with functions, classes, and variables that help in different areas such as data analysis, web development, machine learning, and more. By using libraries, developers can save time and effort by leveraging existing solutions.


We use Python libraries for several reasons:

Efficiency: Libraries provide pre-written, optimized code for common tasks, which saves time and effort. Instead of writing code from scratch, you can use libraries to implement functionality quickly.

Reusability: Libraries offer reusable components that can be used across different projects, promoting code reusability and consistency.

Community Support: Popular libraries are often well-maintained and supported by a large community. This means you can find plenty of documentation, tutorials, and forums to help you understand and use the library effectively.

Reliability: Libraries are usually tested and used by many developers, which means they are more reliable and less prone to bugs compared to custom-written code.

Specialization: Libraries are often specialized for specific tasks or domains, such as data analysis (Pandas), machine learning (Scikit-learn), or web development (Flask). This specialization provides powerful tools tailored to particular needs.

Scalability: Libraries are designed to handle a wide range of tasks, from simple scripts to complex applications, and can scale with the needs of your project.

Standardization: Using libraries helps standardize code, making it easier for others to read, understand, and collaborate on your projects.

Q2. What is the difference between Numpy array and List?

1. Data Type and Homogeneity

NumPy Array: Elements are of the same data type (homogeneous). This allows for efficient storage and computation.


Python List: Elements can be of different data types (heterogeneous). This flexibility comes at the cost of performance.

2. Performance

NumPy Array: More efficient for numerical computations. Operations on NumPy arrays are faster due to the use of optimized C and Fortran libraries under the hood.

Python List: Slower for numerical computations as it is a more general-purpose container.

3. Functionality

NumPy Array: Supports a wide range of mathematical and logical operations directly on arrays. It includes functions for linear algebra, statistical operations, and more.

Python List: Basic operations like append, insert, remove, etc. For numerical operations, you typically need loops or list comprehensions.

4. Memory Usage

NumPy Array: More memory-efficient as it stores elements in a contiguous block of memory.

Python List: Less memory-efficient because it stores references to objects, which can be scattered across memory.

5. Indexing and Slicing

NumPy Array: Supports advanced indexing and slicing, including multidimensional slicing.

Python List: Basic slicing and indexing. Multidimensional indexing requires nested lists.

6. Broadcasting

NumPy Array: Supports broadcasting, which allows for element-wise operations on arrays of different shapes.

Python List: Does not support broadcasting; you need explicit loops for element-wise operations.

7. Usage in Libraries

NumPy Array: Widely used in scientific computing libraries (e.g., SciPy, Pandas) and machine learning frameworks (e.g., TensorFlow, PyTorch).

Python List: General-purpose container, less optimized for numerical and scientific computations.

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [3]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
 
shape = arr.shape
size = arr.size
ndim = arr.ndim

shape,    size,    ndim


((3, 4), 12, 2)

4. Write python co^e to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [ ]:
import numpy as np
 
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
 
first_row = arr[0]

first_row


array([1, 2, 3, 4])

5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [5]:
import numpy as np
 
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
 
element = arr[2, 3]

element


12

6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [7]:
import numpy as np
 
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
 
odd_indexed_elements = arr[1::2, 1::2]

odd_indexed_elements


array([[6, 8]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?


In [9]:
import numpy as np
 
random_matrix = np.random.rand(3, 3)

random_matrix


array([[0.26460404, 0.64668092, 0.60463275],
       [0.45521084, 0.44001159, 0.20701731],
       [0.74509181, 0.09614025, 0.29873499]])

8. Describe the difference between np.random.rand and np.random.randn?

In [11]:
import numpy as np
uniform_array = np.random.rand(3, 3)
print(uniform_array)


[[0.05303973 0.13531087 0.16578058]
 [0.4314641  0.90185682 0.46926225]
 [0.13932444 0.02424624 0.16067664]]


9. Write co^e to increase the ^imension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [12]:
import numpy as np
 
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
 
reshaped_arr = arr.reshape((3, 4, 1))

reshaped_arr


array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [16]:
import numpy as np
 
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
 
transposed_arr = arr.T

transposed_arr



array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [17]:
import numpy as np
 
matrix_A2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

matrix_B2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
 
print("Matrix A2:")
print(matrix_A2)
print("\nMatrix B2:")
print(matrix_B2)
 
addition = matrix_A2 + matrix_B2
print("\nMatrix Addition:")
print(addition)
 
subtraction = matrix_A2 - matrix_B2
print("\nMatrix Subtraction:")
print(subtraction)
 
multiplication = matrix_A2 * matrix_B2
print("\nMatrix Element-wise Multiplication:")
print(multiplication)

 


Matrix A2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix Addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix Subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matrix Element-wise Multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


12.  Which function in Numpy can be use^ to swap the byte or^er of an array?

To swap the byte order of an array in NumPy, you can use the np.ndarray.byteswap() method. This method is used to change the byte order of the array's elements.

13.  What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix

14. What ^oes the np.reshape function ^o, an^ how is it use^?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to specify a new shape for the array, and NumPy will arrange the elements accordingly.

Key Points:
    
Shape Transformation: It rearranges the elements of the array into a new shape.

Data Preservation: The total number of elements must remain the same before and after reshaping.

SYMTAX:

numpy.reshape(a, newshape, order='C')

a: The array to be reshaped.

newshape: The desired shape. It can be a tuple or an integer. If it is a single integer, it will be treated as a 1-D array of that length.

order: The order in which the elements are read and written. 'C' means row-major (C-style) order, 'F' means column-major (Fortran-style) order, and 'A' means ‘F’ order if the array is Fortran contiguous, ‘C’ otherwise.